name: Build and Publish Doxygen Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "docs/Doxyfile-public"
      - "docs/overview.md"
  pull_request:
    paths:
      - "src/**"
      - "docs/Doxyfile-public"
      - "docs/overview.md"

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Doxygen 1.15.0
        id: cache-doxygen
        uses: actions/cache@v4
        with:
          path: doxygen-1.15.0
          key: doxygen-1.15.0

      - name: Install Doxygen 1.15.0 if cache missed
        if: steps.cache-doxygen.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://www.doxygen.nl/files/doxygen-1.15.0.linux.bin.tar.gz
          tar xzf doxygen-1.15.0.linux.bin.tar.gz

      - name: Put Doxygen in PATH
        run: |
          echo "${{ github.workspace }}/doxygen-1.15.0/bin" >> $GITHUB_PATH

      - name: Generate documentation
        run: doxygen docs/Doxyfile-public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/public/html
